[package]
name = "http2_server"
version = "0.1.0"
edition = "2024"

[dependencies]
http-body-util = "0.1.2"
hyper = { version = "1.6.0", features = ["http2", "server"] }
pin-project-lite = "0.2.16"
pretty_env_logger = "0.5.0"
tokio = { version = "1.43.0", features = ["full"] }
